services:
  app:
    build: .
    working_dir: /home/app
    ports:
      - "3000:3000"
      - "9005:9005"
    volumes:
      - .:/home/app
    tty: true
    stdin_open: true
    command: sh -c "yarn install --immutable --immutable-cache --check-cache && yarn dev"
